### ISSUE TITLE
links plugin causing bot to disconnect

### ISSUE THREAD

**Issue by tykeal** [tykeal/TykeBot#6]
More than 18 links saved seems to cause the bot to crash.

I'm pretty certain we had more than that at one point and one of the newer plugins may have introduced something but I haven't run it down.  I just wanted to get this logged.

**Comment by iospera** [comment]
blame becker. I think he introduced the bug :-)

Seriously, i think it started reproing when he started mucking around with using nokogiri

---

From: Andrew Grimberg &lt;reply@reply.github.com&gt;
To: Alan Shield &lt;iospera@yahoo.com&gt;
Sent: Saturday, November 12, 2011 6:07 AM
Subject: [TykeBot] links plugin causing bot to disconnect (#6)

More than 18 links saved seems to cause the bot to crash.

I&#39;m pretty certain we had more than that at one point and one of the newer plugins may have introduced something but I haven&#39;t run it down. I just wanted to get this logged.

---

Reply to this email directly or view it on GitHub:
https://github.com/tykeal/TykeBot/issues/6

**Comment by tykeal** [comment]
That's possible.  I don't know why it would be affecting it though.  We're still saving off links, you just cause the bot to disconnect and run through it's reconnect routines when you request a playback of any number of links.

**Comment by tykeal** [comment]
Just a little update, I spun all the way back to the last checkin on the links plugin ( 92e9ecb96606b80349223be00267c30b7e34a268 ) which was the only checkin for it apparently.  Even that checkin had this particular issue.  So, it's apparently always been there, we just hadn't gotten up to / tested up to that number of links saved off.

**Comment by sbeckeriv** [comment]
I'm good for Time issues but not off by 18 issues :)
